### ISSUE TITLE
002、019代码存在不足！

### ISSUE THREAD

**Issue by BigMoWangying** [BigMoWangying/leetcode#1]
:warning: 内存泄露 memory leak
链表的操作需要进一步完善

**Comment by HugueLiu** [comment]
你个菜鸡儿，这么简单的问题，赶紧fix :-1:

**Comment by BigMoWangying** [comment]
:1234: fixed problem:
- [x] 019 
- [ ] 002

> 002代码写得太恶心，找个时间重写

**Comment by BigMoWangying** [comment]
002不改了，直接参考 @HugueLiu 的答案
